server.port=${PORT:8080}
spring.application.name=portfolio


# PostgreSQL
spring.datasource.url=jdbc:postgresql://db.elrmhbhcqqoovexxtoph.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=mr9hCOAuGHfzLJgB
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=no.reply.lms0@gmail.com
spring.mail.password=cankyqspyejinkxh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
